### ISSUE TITLE
Regarding the .h5 Files in the Data Folder

### ISSUE THREAD

**Issue by GaoHaokai222** [iLearn-Lab/TIP23-ARC#3]
Hi,

Thank you for your outstanding work. However, I didn't quite understand where I can find the .h5 files in the data folder. Could you please provide me with some guidance on how to access these files?

Thank you in advance for your help.

**Comment by SDLZY** [comment]
Regarding the self.qr2a_h5 file you mentioned, the relevant link is in the data folder of the corresponding model, namely ARC/r2c_kd/data and ARC/ccn_kd/data. You can download it from Google Drive and place it in the corresponding local folder to run it.

**Comment by GaoHaokai222** [comment]
Thanks for your response. I have downloaded the corresponding files.
